PC1:
  MAC: AA:BB:CC:CC:DD:EE
  IP_addr: 192.168.1.3
  slp_time: 30
  ping_num: 30

PC2:
  MAC: AA:BB:CC:CC:DD:EE
  IP_addr: 192.168.1.4
  slp_time: 20
  ping_num: 20

PC3:
  MAC: AA:BB:CC:CC:DD:EE
  IP_addr: 192.168.1.2
  slp_time: 40
  ping_num: 20

PC4:
  MAC: AA:BB:CC:CC:DD:EE
  IP_addr: 192.168.1.5
  slp_time: 40
  ping_num: 20
